apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld-app
spec:
  selector:
    app: helloworld-app
    version: blue
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30000
